import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaFileAlt, FaTimes, FaDownload, FaSpinner, FaEye, FaEdit } from 'react-icons/fa';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

/* ─── Resume Preview Template (rendered off-screen then captured) ─── */
const ResumeTemplate = React.forwardRef(({ data }, ref) => (
  <div ref={ref} style={{
    width: '794px', minHeight: '1123px', background: '#fff',
    fontFamily: 'Arial, sans-serif', fontSize: '13px', color: '#1a1a1a',
    padding: 0, boxSizing: 'border-box', position: 'absolute', left: '-9999px', top: 0
  }}>
    {/* Header */}
    <div style={{ background: 'linear-gradient(135deg, #002D8B, #003399)', color: '#fff', padding: '32px 40px 24px' }}>
      <h1 style={{ margin: 0, fontSize: '28px', fontWeight: 700, letterSpacing: 1 }}>{data.fullName || 'Your Name'}</h1>
      <div style={{ display: 'flex', gap: '24px', marginTop: '10px', flexWrap: 'wrap', fontSize: '12px', opacity: 0.9 }}>
        {data.email && <span>✉ {data.email}</span>}
        {data.phone && <span>📞 {data.phone}</span>}
        {data.linkedin && <span>🔗 {data.linkedin}</span>}
        {data.github && <span>💻 {data.github}</span>}
      </div>
    </div>

    <div style={{ padding: '28px 40px', display: 'grid', gridTemplateColumns: '1fr 1.4fr', gap: '28px' }}>
      {/* Left column */}
      <div>
        {data.objective && <Section title="Career Objective" accent="#002D8B">
          <p style={{ margin: 0, lineHeight: 1.7, color: '#333' }}>{data.objective}</p>
        </Section>}

        {data.skills && <Section title="Skills" accent="#002D8B">
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
            {data.skills.split(',').map((s, i) => s.trim() && (
              <span key={i} style={{ background: 'rgba(0,51,153,0.1)', color: '#002D8B', padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: 600 }}>
                {s.trim()}
              </span>
            ))}
          </div>
        </Section>}

        {data.certifications && <Section title="Certifications" accent="#99CC00">
          {data.certifications.split('\n').filter(Boolean).map((c, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '6px', marginBottom: '6px' }}>
              <span style={{ color: '#99CC00', fontWeight: 700, marginTop: 1 }}>▸</span>
              <span style={{ color: '#333' }}>{c}</span>
            </div>
          ))}
        </Section>}
      </div>

      {/* Right column */}
      <div>
        {data.education && <Section title="Education" accent="#99CC00">
          {data.education.split('\n').filter(Boolean).map((e, i) => (
            <p key={i} style={{ margin: '0 0 6px', color: '#333' }}>{e}</p>
          ))}
        </Section>}

        {data.experience && <Section title="Experience" accent="#002D8B">
          {data.experience.split('\n').filter(Boolean).map((e, i) => (
            <div key={i} style={{ display: 'flex', gap: '6px', marginBottom: '8px' }}>
              <span style={{ color: '#002D8B', fontWeight: 700, marginTop: 1 }}>▸</span>
              <span style={{ color: '#333', lineHeight: 1.6 }}>{e}</span>
            </div>
          ))}
        </Section>}

        {data.projects && <Section title="Projects" accent="#99CC00">
          {data.projects.split('\n').filter(Boolean).map((p, i) => (
            <div key={i} style={{ marginBottom: '10px' }}>
              <div style={{ display: 'flex', gap: '6px' }}>
                <span style={{ color: '#99CC00', fontWeight: 700, marginTop: 1 }}>▸</span>
                <span style={{ color: '#333', lineHeight: 1.6 }}>{p}</span>
              </div>
            </div>
          ))}
        </Section>}
      </div>
    </div>

    {/* Footer */}
    <div style={{ background: '#f5f7ff', borderTop: '3px solid #99CC00', padding: '12px 40px', textAlign: 'center', fontSize: '11px', color: '#666' }}>
      Generated by KeeZ Campus · Learn • Build • Grow
    </div>
  </div>
));

const Section = ({ title, children, accent }) => (
  <div style={{ marginBottom: '20px' }}>
    <h3 style={{ margin: '0 0 10px', fontSize: '13px', fontWeight: 700, color: accent, textTransform: 'uppercase', letterSpacing: '1px', borderBottom: `2px solid ${accent}`, paddingBottom: '4px' }}>
      {title}
    </h3>
    {children}
  </div>
);

/* ─── Main Component ─── */
const ResumeBuilder = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [step, setStep] = useState('form'); // 'form' | 'preview'
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({
    fullName: '', email: '', phone: '',
    linkedin: '', github: '', objective: '',
    skills: '', education: '', experience: '',
    certifications: '', projects: ''
  });

  const resumeRef = useRef(null);

  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });

  const handleGenerate = async () => {
    if (!form.fullName || !form.email) {
      alert('Please fill in at least your Full Name and Email.');
      return;
    }
    setLoading(true);
    await new Promise(r => setTimeout(r, 1200)); // simulate generation
    setStep('preview');
    setLoading(false);
  };

  const handleDownload = async () => {
    if (!resumeRef.current) return;
    setLoading(true);
    try {
      const canvas = await html2canvas(resumeRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: [794, 1123] });
      pdf.addImage(imgData, 'PNG', 0, 0, 794, 1123);
      pdf.save(`${form.fullName || 'resume'}_KeeZ_Campus.pdf`);
    } catch (err) {
      alert('Error generating PDF. Please try again.');
    }
    setLoading(false);
  };

  const inputStyle = {
    width: '100%', padding: '0.6rem 0.875rem', borderRadius: '0.4rem',
    border: '1.5px solid #E2E8F0', outline: 'none', fontSize: '0.85rem',
    fontFamily: 'inherit', background: '#F8FAFC', color: '#1E293B', boxSizing: 'border-box'
  };

  const fields = [
    { name: 'fullName', label: 'Full Name *', placeholder: 'Bharath Goud', type: 'input' },
    { name: 'email', label: 'Email *', placeholder: 'your@email.com', type: 'input' },
    { name: 'phone', label: 'Phone', placeholder: '+91 9XXXXXXXXX', type: 'input' },
    { name: 'linkedin', label: 'LinkedIn URL', placeholder: 'linkedin.com/in/you', type: 'input' },
    { name: 'github', label: 'GitHub URL', placeholder: 'github.com/you', type: 'input' },
    { name: 'objective', label: 'Career Objective', placeholder: 'Aspiring developer with passion for...', type: 'textarea' },
    { name: 'skills', label: 'Skills (comma separated)', placeholder: 'React, Node.js, Python, MongoDB', type: 'textarea' },
    { name: 'education', label: 'Education (one per line)', placeholder: 'B.Tech CSE, XYZ University, 2024', type: 'textarea' },
    { name: 'experience', label: 'Experience (one per line)', placeholder: 'Software Intern @ ABC Corp, 2023', type: 'textarea' },
    { name: 'certifications', label: 'Certifications (one per line)', placeholder: 'AWS Certified Cloud Practitioner', type: 'textarea' },
    { name: 'projects', label: 'Projects (one per line)', placeholder: 'E-Commerce App: Built with React & Node', type: 'textarea' },
  ];

  return (
    <>
      {/* Hidden resume template for PDF capture */}
      <ResumeTemplate ref={resumeRef} data={form} />

      {/* Floating Button */}
      <motion.button
        onClick={() => { setIsOpen(true); setStep('form'); }}
        initial={{ scale: 0, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ delay: 2, type: 'spring', stiffness: 200 }}
        whileHover={{ scale: 1.08, boxShadow: '0 10px 30px rgba(0,51,153,0.45)' }}
        whileTap={{ scale: 0.95 }}
        style={{
          position: 'fixed', bottom: '2rem', left: '2rem', zIndex: 999,
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          padding: '0.875rem 1.5rem',
          background: 'linear-gradient(135deg, #003399, #002D8B)',
          color: 'white', border: '1px solid rgba(153,204,0,0.4)',
          borderRadius: '3rem', cursor: 'pointer',
          fontWeight: 700, fontSize: '0.9rem', fontFamily: 'inherit',
          boxShadow: '0 8px 20px rgba(0,51,153,0.35)'
        }}
      >
        <FaFileAlt /> Build Resume
      </motion.button>

      {/* Modal */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            style={{ position: 'fixed', inset: 0, zIndex: 2000, background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}
          >
            <motion.div
              initial={{ scale: 0.88, opacity: 0, y: 40 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.88, opacity: 0, y: 40 }}
              transition={{ type: 'spring', damping: 22, stiffness: 200 }}
              style={{ background: '#fff', borderRadius: '1rem', width: '100%', maxWidth: '620px', maxHeight: '88vh', overflowY: 'auto', boxShadow: '0 30px 70px rgba(0,0,0,0.4)', position: 'relative' }}
            >
              {/* Header */}
              <div style={{ padding: '1.5rem 2rem', background: 'linear-gradient(135deg, #002D8B, #003399)', borderRadius: '1rem 1rem 0 0', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, zIndex: 10 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <FaFileAlt size={20} color="#99CC00" />
                  <div>
                    <h3 style={{ margin: 0, color: 'white', fontSize: '1.1rem' }}>Resume Builder</h3>
                    <p style={{ margin: 0, color: 'rgba(255,255,255,0.7)', fontSize: '0.75rem' }}>
                      {step === 'form' ? 'Fill your details → Generate PDF' : 'Preview your resume below'}
                    </p>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
                  {step === 'preview' && (
                    <motion.button whileHover={{ scale: 1.05 }} onClick={() => setStep('form')} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', color: 'white', padding: '0.4rem 1rem', borderRadius: '2rem', cursor: 'pointer', fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '0.4rem', fontFamily: 'inherit' }}>
                      <FaEdit size={12} /> Edit
                    </motion.button>
                  )}
                  <button onClick={() => setIsOpen(false)} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', color: 'white', width: '32px', height: '32px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <FaTimes size={14} />
                  </button>
                </div>
              </div>

              {/* Body */}
              <div style={{ padding: '1.75rem 2rem 2rem' }}>
                <AnimatePresence mode="wait">
                  {step === 'form' ? (
                    <motion.div key="form" initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} transition={{ duration: 0.3 }}>
                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                        {fields.slice(0, 2).map(f => (
                          <div key={f.name}>
                            <label style={{ display: 'block', fontSize: '0.78rem', fontWeight: 600, color: '#374151', marginBottom: '0.35rem' }}>{f.label}</label>
                            <input name={f.name} placeholder={f.placeholder} value={form[f.name]} onChange={handleChange} style={inputStyle} />
                          </div>
                        ))}
                      </div>
                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                        {fields.slice(2, 4).map(f => (
                          <div key={f.name}>
                            <label style={{ display: 'block', fontSize: '0.78rem', fontWeight: 600, color: '#374151', marginBottom: '0.35rem' }}>{f.label}</label>
                            <input name={f.name} placeholder={f.placeholder} value={form[f.name]} onChange={handleChange} style={inputStyle} />
                          </div>
                        ))}
                      </div>
                      <div style={{ marginBottom: '1rem' }}>
                        <label style={{ display: 'block', fontSize: '0.78rem', fontWeight: 600, color: '#374151', marginBottom: '0.35rem' }}>GitHub URL</label>
                        <input name="github" placeholder="github.com/you" value={form.github} onChange={handleChange} style={inputStyle} />
                      </div>
                      {fields.slice(5).map(f => (
                        <div key={f.name} style={{ marginBottom: '1rem' }}>
                          <label style={{ display: 'block', fontSize: '0.78rem', fontWeight: 600, color: '#374151', marginBottom: '0.35rem' }}>{f.label}</label>
                          <textarea name={f.name} placeholder={f.placeholder} value={form[f.name]} onChange={handleChange} rows={3} style={{ ...inputStyle, resize: 'vertical' }} />
                        </div>
                      ))}

                      <motion.button
                        whileHover={{ scale: 1.02, boxShadow: '0 10px 25px rgba(0,51,153,0.3)' }}
                        whileTap={{ scale: 0.98 }}
                        onClick={handleGenerate}
                        disabled={loading}
                        style={{ width: '100%', padding: '1rem', background: 'linear-gradient(90deg, #003399, #002D8B)', color: 'white', border: 'none', borderRadius: '0.5rem', fontWeight: 700, fontSize: '1rem', cursor: 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem', marginTop: '0.5rem' }}
                      >
                        {loading ? <><FaSpinner style={{ animation: 'spin 1s linear infinite' }} /> Building Resume...</> : <><FaEye /> Preview Resume</>}
                      </motion.button>
                    </motion.div>

                  ) : (
                    <motion.div key="preview" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 20 }} transition={{ duration: 0.3 }}>
                      {/* Inline preview (scaled) */}
                      <div style={{ background: '#f1f5f9', borderRadius: '0.5rem', padding: '1rem', marginBottom: '1.5rem', overflow: 'auto', maxHeight: '55vh' }}>
                        <div style={{ transform: 'scale(0.68)', transformOrigin: 'top left', width: '147%' }}>
                          <div style={{ width: '794px', background: '#fff', fontFamily: 'Arial, sans-serif', fontSize: '13px', color: '#1a1a1a', borderRadius: '4px', overflow: 'hidden' }}>
                            <div style={{ background: 'linear-gradient(135deg, #002D8B, #003399)', color: '#fff', padding: '32px 40px 24px' }}>
                              <h1 style={{ margin: 0, fontSize: '28px', fontWeight: 700 }}>{form.fullName || 'Your Name'}</h1>
                              <div style={{ display: 'flex', gap: '20px', marginTop: '10px', flexWrap: 'wrap', fontSize: '12px', opacity: 0.9 }}>
                                {form.email && <span>✉ {form.email}</span>}
                                {form.phone && <span>📞 {form.phone}</span>}
                                {form.linkedin && <span>🔗 {form.linkedin}</span>}
                                {form.github && <span>💻 {form.github}</span>}
                              </div>
                            </div>
                            <div style={{ padding: '28px 40px', display: 'grid', gridTemplateColumns: '1fr 1.4fr', gap: '28px' }}>
                              <div>
                                {form.objective && <div style={{ marginBottom: '16px' }}><h3 style={{ fontSize: '12px', color: '#002D8B', borderBottom: '2px solid #002D8B', paddingBottom: '4px', marginBottom: '8px' }}>CAREER OBJECTIVE</h3><p style={{ margin: 0, lineHeight: 1.7, color: '#333' }}>{form.objective}</p></div>}
                                {form.skills && <div style={{ marginBottom: '16px' }}><h3 style={{ fontSize: '12px', color: '#002D8B', borderBottom: '2px solid #002D8B', paddingBottom: '4px', marginBottom: '8px' }}>SKILLS</h3><div style={{ display: 'flex', flexWrap: 'wrap', gap: '5px' }}>{form.skills.split(',').map((s, i) => s.trim() && <span key={i} style={{ background: 'rgba(0,51,153,0.1)', color: '#002D8B', padding: '2px 8px', borderRadius: '10px', fontSize: '11px', fontWeight: 600 }}>{s.trim()}</span>)}</div></div>}
                                {form.certifications && <div style={{ marginBottom: '16px' }}><h3 style={{ fontSize: '12px', color: '#99CC00', borderBottom: '2px solid #99CC00', paddingBottom: '4px', marginBottom: '8px' }}>CERTIFICATIONS</h3>{form.certifications.split('\n').filter(Boolean).map((c, i) => <p key={i} style={{ margin: '0 0 4px', color: '#333' }}>▸ {c}</p>)}</div>}
                              </div>
                              <div>
                                {form.education && <div style={{ marginBottom: '16px' }}><h3 style={{ fontSize: '12px', color: '#99CC00', borderBottom: '2px solid #99CC00', paddingBottom: '4px', marginBottom: '8px' }}>EDUCATION</h3>{form.education.split('\n').filter(Boolean).map((e, i) => <p key={i} style={{ margin: '0 0 6px', color: '#333' }}>{e}</p>)}</div>}
                                {form.experience && <div style={{ marginBottom: '16px' }}><h3 style={{ fontSize: '12px', color: '#002D8B', borderBottom: '2px solid #002D8B', paddingBottom: '4px', marginBottom: '8px' }}>EXPERIENCE</h3>{form.experience.split('\n').filter(Boolean).map((e, i) => <p key={i} style={{ margin: '0 0 6px', color: '#333' }}>▸ {e}</p>)}</div>}
                                {form.projects && <div style={{ marginBottom: '16px' }}><h3 style={{ fontSize: '12px', color: '#99CC00', borderBottom: '2px solid #99CC00', paddingBottom: '4px', marginBottom: '8px' }}>PROJECTS</h3>{form.projects.split('\n').filter(Boolean).map((p, i) => <p key={i} style={{ margin: '0 0 6px', color: '#333' }}>▸ {p}</p>)}</div>}
                              </div>
                            </div>
                            <div style={{ background: '#f5f7ff', borderTop: '3px solid #99CC00', padding: '10px 40px', textAlign: 'center', fontSize: '10px', color: '#666' }}>Generated by KeeZ Campus · Learn • Build • Grow</div>
                          </div>
                        </div>
                      </div>

                      <motion.button
                        whileHover={{ scale: 1.03, boxShadow: '0 10px 25px rgba(153,204,0,0.4)' }}
                        whileTap={{ scale: 0.98 }}
                        onClick={handleDownload}
                        disabled={loading}
                        style={{ width: '100%', padding: '1rem', background: 'linear-gradient(90deg, #6b8f00, #99CC00)', color: '#002D8B', border: 'none', borderRadius: '0.5rem', fontWeight: 800, fontSize: '1rem', cursor: 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem' }}
                      >
                        {loading ? <><FaSpinner style={{ animation: 'spin 1s linear infinite' }} /> Generating PDF...</> : <><FaDownload /> Download Resume (PDF)</>}
                      </motion.button>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </>
  );
};

export default ResumeBuilder;
